## description: Fast Portable Noise Library - C# C++ C Java HLSL GLSL JavaScript Rust Go

function(dep LIBRARY_MACRO_NAME SHARED_LIB STATIC_LIB STATIC_PROFILE_LIB INCLUDE_PATHS)
    set(LIB_NAME FastNeuseLite)
    set(LIB_MACRO_NAME FAST_NOISE_LITE_LIBRARY_AVAILABLE)
    set(GIT_REPO https://github.com/Auburn/FastNoiseLite.git)
    set(GIT_TAG master)

    smartDeclare(${LIB_NAME} ${GIT_REPO} ${GIT_TAG})
    FetchContent_MakeAvailable(${LIB_NAME})

    string(TOLOWER ${LIB_NAME} LIB_NAME_LOWER)
    list(APPEND INCLUDES ${${LIB_NAME_LOWER}_SOURCE_DIR}/Cpp)

    set(${LIBRARY_MACRO_NAME} "${${LIBRARY_MACRO_NAME}};${LIB_MACRO_NAME}" PARENT_SCOPE)
    set(${INCLUDE_PATHS} "${${INCLUDE_PATHS}};${INCLUDES}" PARENT_SCOPE)
endfunction()

dep(DEPENDENCY_NAME_MACRO
    DEPENDENCIES_FOR_SHARED_LIB
    DEPENDENCIES_FOR_STATIC_LIB
    DEPENDENCIES_FOR_STATIC_PROFILE_LIB
    DEPENDENCIES_INCLUDE_PATHS)
