#pragma once

/// USER_SECTION_START 1

/// USER_SECTION_END

// Debugging
#ifdef NDEBUG
	#define LIBRARY_NAME_SHORT_CONSOLE(msg)
	#define LIBRARY_NAME_SHORT_CONSOLE_FUNCTION(msg)
#else
	#include <iostream>

	#define LIBRARY_NAME_SHORT_DEBUG
	#define LIBRARY_NAME_SHORT_CONSOLE_STREAM std::cout

	#define LIBRARY_NAME_SHORT_CONSOLE(msg) LIBRARY_NAME_SHORT_CONSOLE_STREAM << msg;
	#define LIBRARY_NAME_SHORT_CONSOLE_FUNCTION(msg) LIBRARY_NAME_SHORT_CONSOLE_STREAM << __PRETTY_FUNCTION__ << " " << msg;
#endif

/// USER_SECTION_START 2

/// USER_SECTION_END

#ifdef LIBRARY_NAME_SHORT_PROFILING
	#include "easy/profiler.h"
	#include <easy/arbitrary_value.h> // EASY_VALUE, EASY_ARRAY are defined here

	#define LIBRARY_NAME_SHORT_PROFILING_BLOCK_C(text, color) EASY_BLOCK(text, color)
	#define LIBRARY_NAME_SHORT_PROFILING_NONSCOPED_BLOCK_C(text, color) EASY_NONSCOPED_BLOCK(text, color)
	#define LIBRARY_NAME_SHORT_PROFILING_END_BLOCK EASY_END_BLOCK
	#define LIBRARY_NAME_SHORT_PROFILING_FUNCTION_C(color) EASY_FUNCTION(color)
	#define LIBRARY_NAME_SHORT_PROFILING_BLOCK(text, colorStage) LIBRARY_NAME_SHORT_PROFILING_BLOCK_C(text,profiler::colors::  colorStage)
	#define LIBRARY_NAME_SHORT_PROFILING_NONSCOPED_BLOCK(text, colorStage) LIBRARY_NAME_SHORT_PROFILING_NONSCOPED_BLOCK_C(text,profiler::colors::  colorStage)
	#define LIBRARY_NAME_SHORT_PROFILING_FUNCTION(colorStage) LIBRARY_NAME_SHORT_PROFILING_FUNCTION_C(profiler::colors:: colorStage)
	#define LIBRARY_NAME_SHORT_PROFILING_THREAD(name) EASY_THREAD(name)

	#define LIBRARY_NAME_SHORT_PROFILING_VALUE(name, value) EASY_VALUE(name, value)
	#define LIBRARY_NAME_SHORT_PROFILING_TEXT(name, value) EASY_TEXT(name, value)

#else
	#define LIBRARY_NAME_SHORT_PROFILING_BLOCK_C(text, color)
	#define LIBRARY_NAME_SHORT_PROFILING_NONSCOPED_BLOCK_C(text, color)
	#define LIBRARY_NAME_SHORT_PROFILING_END_BLOCK
	#define LIBRARY_NAME_SHORT_PROFILING_FUNCTION_C(color)
	#define LIBRARY_NAME_SHORT_PROFILING_BLOCK(text, colorStage)
	#define LIBRARY_NAME_SHORT_PROFILING_NONSCOPED_BLOCK(text, colorStage)
	#define LIBRARY_NAME_SHORT_PROFILING_FUNCTION(colorStage)
	#define LIBRARY_NAME_SHORT_PROFILING_THREAD(name)

	#define LIBRARY_NAME_SHORT_PROFILING_VALUE(name, value)
	#define LIBRARY_NAME_SHORT_PROFILING_TEXT(name, value)
#endif

// Special expantion tecniques are required to combine the color name
#define CONCAT_SYMBOLS_IMPL(x, y) x##y
#define CONCAT_SYMBOLS(x, y) CONCAT_SYMBOLS_IMPL(x, y)



// Different color stages
#define LIBRARY_NAME_SHORT_COLOR_STAGE_1 50
#define LIBRARY_NAME_SHORT_COLOR_STAGE_2 100
#define LIBRARY_NAME_SHORT_COLOR_STAGE_3 200
#define LIBRARY_NAME_SHORT_COLOR_STAGE_4 300
#define LIBRARY_NAME_SHORT_COLOR_STAGE_5 400
#define LIBRARY_NAME_SHORT_COLOR_STAGE_6 500
#define LIBRARY_NAME_SHORT_COLOR_STAGE_7 600
#define LIBRARY_NAME_SHORT_COLOR_STAGE_8 700
#define LIBRARY_NAME_SHORT_COLOR_STAGE_9 800
#define LIBRARY_NAME_SHORT_COLOR_STAGE_10 900
#define LIBRARY_NAME_SHORT_COLOR_STAGE_11 A100 
#define LIBRARY_NAME_SHORT_COLOR_STAGE_12 A200 
#define LIBRARY_NAME_SHORT_COLOR_STAGE_13 A400 
#define LIBRARY_NAME_SHORT_COLOR_STAGE_14 A700 


// General
#define LIBRARY_NAME_SHORT_GENERAL_PROFILING_COLORBASE Cyan
#define LIBRARY_NAME_SHORT_GENERAL_PROFILING_BLOCK_C(text, color) LIBRARY_NAME_SHORT_PROFILING_BLOCK_C(text, color)
#define LIBRARY_NAME_SHORT_GENERAL_PROFILING_NONSCOPED_BLOCK_C(text, color) LIBRARY_NAME_SHORT_PROFILING_NONSCOPED_BLOCK_C(text, color)
#define LIBRARY_NAME_SHORT_GENERAL_PROFILING_END_BLOCK LIBRARY_NAME_SHORT_PROFILING_END_BLOCK;
#define LIBRARY_NAME_SHORT_GENERAL_PROFILING_FUNCTION_C(color) LIBRARY_NAME_SHORT_PROFILING_FUNCTION_C(color)
#define LIBRARY_NAME_SHORT_GENERAL_PROFILING_BLOCK(text, colorStage) LIBRARY_NAME_SHORT_PROFILING_BLOCK(text, CONCAT_SYMBOLS(LIBRARY_NAME_SHORT_GENERAL_PROFILING_COLORBASE, colorStage))
#define LIBRARY_NAME_SHORT_GENERAL_PROFILING_NONSCOPED_BLOCK(text, colorStage) LIBRARY_NAME_SHORT_PROFILING_NONSCOPED_BLOCK(text, CONCAT_SYMBOLS(LIBRARY_NAME_SHORT_GENERAL_PROFILING_COLORBASE, colorStage))
#define LIBRARY_NAME_SHORT_GENERAL_PROFILING_FUNCTION(colorStage) LIBRARY_NAME_SHORT_PROFILING_FUNCTION(CONCAT_SYMBOLS(LIBRARY_NAME_SHORT_GENERAL_PROFILING_COLORBASE, colorStage))
#define LIBRARY_NAME_SHORT_GENERAL_PROFILING_VALUE(name, value) LIBRARY_NAME_SHORT_PROFILING_VALUE(name, value)
#define LIBRARY_NAME_SHORT_GENERAL_PROFILING_TEXT(name, value) LIBRARY_NAME_SHORT_PROFILING_TEXT(name, value)


/// USER_SECTION_START 3

/// USER_SECTION_END